
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod(operationName = "AccountList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountList", targetNamespace = "http://ws/", className = "proxy.AccountList")
    @ResponseWrapper(localName = "AccountListResponse", targetNamespace = "http://ws/", className = "proxy.AccountListResponse")
    @Action(input = "http://ws/BankService/AccountListRequest", output = "http://ws/BankService/AccountListResponse")
    public List<Account> accountList();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "proxy.GetAccountResponse")
    @Action(input = "http://ws/BankService/getAccountRequest", output = "http://ws/BankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://ws/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://ws/", className = "proxy.ConversionResponse")
    @Action(input = "http://ws/BankService/conversionRequest", output = "http://ws/BankService/conversionResponse")
    public double conversion(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

}
